const skills = [
  {
    slug: 'industry-education-report',
    name: '产教决策报告',
    identifier: 'industry-education-report',
    summary: '面向院校、政府和园区生成有证据、可审查的产业与专业建设决策报告。',
    category: '产业与专业建设',
    tags: ['产教融合', '专业建设', '决策报告'],
    compatibility: ['Codex'],
    dependencies: ['可信的产业、岗位、专业或就业资料', 'Python 3（运行报告校验脚本时）'],
    limitations: ['最新报告需要重新核验来源、年份、范围和统计口径。', '缺少院校微观数据时会保留缺口，不编造就业率、岗位缺口或招生规模。'],
    installation: ['从公开 GitHub 仓库获取完整目录。', '安装时保留 SKILL.md、references、assets 和 scripts 等配套文件。'],
    installPrompt: '请从 https://github.com/Lntanohuang/industry-education-report-skill.git 安装 industry-education-report SKILL，保留仓库完整目录，并在安装后检查依赖、说明调用方式。',
    minimalInput: '使用 $industry-education-report，为广东省某高职院校制作新能源汽车专业建设报告，受众为院校管理者，基期为 2024 年。',
    repository: 'https://github.com/Lntanohuang/industry-education-report-skill.git',
    repositoryLabel: 'Lntanohuang/industry-education-report-skill',
    output: '交付报告 Markdown、结构化 report.json、证据与口径附录，以及结构和语义验收结果。',
    featured: true,
    updatedAt: null,
    kind: 'industry'
  },
  {
    slug: 'classroom-assistant',
    name: '课堂助教',
    identifier: 'classroom-assistant',
    summary: '在授权课程资料范围内完成带引用答疑、要点总结、练习生成和答疑记录整理。',
    category: '课程与教学开发',
    tags: ['课程资料', '课堂练习', '引用答疑'],
    compatibility: ['Codex'],
    dependencies: ['本次明确授权的课程材料；未提供时可使用随包示例知识库'],
    limitations: ['不会用模型记忆或联网搜索补充课程事实。', '资料不足或越界内容会说明缺口并列入待教师处理清单。'],
    installation: ['从公开 GitHub 仓库获取完整目录。', '安装时保留 SKILL.md、references 等课程知识库与规则文件。'],
    installPrompt: '请从 https://github.com/Lntanohuang/classroom-assistant-skill.git 安装 classroom-assistant SKILL，保留仓库完整目录，并在安装后检查依赖、说明调用方式。',
    minimalInput: '使用 $classroom-assistant，基于我提供的《人工智能导论》第 1 章生成 3 道课堂练习并附参考答案和定位引用。',
    repository: 'https://github.com/Lntanohuang/classroom-assistant-skill.git',
    repositoryLabel: 'Lntanohuang/classroom-assistant-skill',
    output: '输出带定位引用的答复、课程资料要点、课堂练习，或待教师处理清单。',
    featured: true,
    updatedAt: null,
    kind: 'teaching'
  },
  {
    slug: 'ai-interview',
    name: 'AI 面试练习',
    identifier: 'ai-interview',
    summary: '结合目标岗位、岗位要求和简历开展逐题模拟面试、智能追问与证据化复盘。',
    category: '实训与就业',
    tags: ['模拟面试', '就业辅导', '回答复盘'],
    compatibility: ['Codex'],
    dependencies: ['目标岗位', '简历或匿名经历摘要；岗位要求可选'],
    limitations: ['评分只衡量本次回答表现，不代表录用概率或个人总体能力。', '不会代替用户作答，也不会自动上传简历或面试内容。'],
    installation: ['从公开 GitHub 仓库获取完整目录。', '安装时保留 SKILL.md、references 和 examples 等配套文件。'],
    installPrompt: '请从 https://github.com/Lntanohuang/ai-interview-skill.git 安装 ai-interview SKILL，保留仓库完整目录，并在安装后检查依赖、说明调用方式。',
    minimalInput: '使用 $ai-interview，目标岗位是 Java 后端实习生，岗位要求和匿名简历见附件，请开始 3 题模拟面试。',
    repository: 'https://github.com/Lntanohuang/ai-interview-skill.git',
    repositoryLabel: 'Lntanohuang/ai-interview-skill',
    output: '输出岗位能力地图、逐题问答与针对性追问，并引用真实回答形成练习报告和改进建议。',
    featured: true,
    updatedAt: null,
    kind: 'interview'
  },
  {
    slug: 'training-data-qa',
    name: '训练样本构造与标注质检',
    identifier: 'training-data-qa',
    summary: '从治理数据构造可追溯训练样本，检查重复、泄漏、分布和业务规则并编排专家抽检。',
    category: '数据治理与模型底座',
    tags: ['数据治理', '标注质检', '训练数据'],
    compatibility: ['Codex', 'Python'],
    dependencies: ['治理数据、任务模板和标注规则', 'Python 3 与 jsonschema>=4.18,<5'],
    limitations: ['未经专家确认的生成结果只能标为候选。', '负责数据构造与验收，不负责执行模型训练。'],
    installation: ['从公开 GitHub 仓库获取完整目录。', '安装仓库 requirements.txt，或为独立 SKILL 安装指定版本的 jsonschema。'],
    installPrompt: '请从 https://github.com/Lntanohuang/training-data-qa.git 安装 training-data-qa SKILL，保留仓库完整目录，并在安装后检查依赖、说明调用方式。',
    minimalInput: '使用 $training-data-qa，基于附件中的客服问答数据和标注规则构造 200 条候选黄金种子，并输出泄漏、重复和分布质检报告。',
    repository: 'https://github.com/Lntanohuang/training-data-qa.git',
    repositoryLabel: 'Lntanohuang/training-data-qa',
    output: '交付四类数据集、质检报告、问题样本、专家抽检任务，以及可追溯版本记录。',
    featured: true,
    updatedAt: null,
    kind: 'data'
  }
];

const categories = ['全部', '产业与专业建设', '课程与教学开发', '实训与就业', '数据治理与模型底座'];
