const skills = [
  {slug:'foru-web-ui',name:'FORU 平台页面',identifier:'foru-web-ui',summary:'以浅蓝白底、角色入口和资源卡片构建中文平台页面。',category:'设计与页面',tags:['FORU','角色入口','平台页面'],compatibility:['Codex'],dependencies:['现代浏览器','沿用目标项目的前端技术栈'],limitations:['复用设计语言，不声称获取原站源码。','插画可近似重建；登录、业务接口与下载需单独接入。'],installation:['将完整 SKILL 目录加入 Codex skills 目录。','提供业务目标、必要模块与目标品牌内容。'],example:'使用 $foru-web-ui，为 SKILL 广场制作响应式 demo。保留原生 HTML/CSS/JS，加入角色入口、检索目录、联动预览和使用指南，不接入第三方业务 API。',output:'输出蓝白平台页面、角色产品面板和功能联动预览。',featured:true,updatedAt:null,kind:'foru'},
  {slug:'deepseek-homepage-ui',name:'DeepSeek 首页风格',identifier:'deepseek-homepage-ui',summary:'使用冰蓝环境、玻璃控件和克制文案构建公开展示页面。',category:'设计与页面',tags:['landing page','响应式','视觉规范'],compatibility:['Codex'],dependencies:['现代浏览器','目标项目的前端运行环境'],limitations:['适用于公开展示页面，不用于高密度 Agent 操作界面。','不会复制第三方品牌标识或未授权素材。'],installation:['将完整 SKILL 目录放入 Codex skills 目录。','在任务中说明页面目标、技术栈与需要保留的品牌内容。'],example:'使用 $deepseek-homepage-ui，把现有产品首页改为冰蓝、克制的技术展示页。保留现有信息架构，并适配 390px 移动端。',output:'输出包含首屏环境层、固定导航、精选媒体、移动端菜单和减少动态效果适配。',featured:true,updatedAt:null,kind:'page'},
  {slug:'architecture-diagram',name:'架构图生成',identifier:'architecture-diagram',summary:'把系统组件、数据流与信任边界整理为可分享的深色架构图。',category:'设计与页面',tags:['架构','SVG','系统设计'],compatibility:['Codex','浏览器'],dependencies:['可打开 HTML 与 SVG 的浏览器'],limitations:['输入缺少边界或依赖关系时，需要先补充系统事实。'],installation:['将完整 SKILL 目录放入 Codex skills 目录。','提供组件、连接关系和需要强调的边界。'],example:'使用 $architecture-diagram，画出 Web 应用、API、队列和数据仓库之间的数据流，并标出公网与私网边界。',output:'生成自包含 HTML + SVG 文件，可在浏览器中查看和分享。',featured:false,updatedAt:null,kind:'diagram'},
  {slug:'sites-building',name:'Sites 网站构建',identifier:'sites-building',summary:'从页面目标出发，完成网站实现、响应式适配与可用预览。',category:'开发工具',tags:['网站','React','部署'],compatibility:['Codex','Sites'],dependencies:['Node.js','Sites 项目环境'],limitations:['外部数据、身份验证和持久化需要单独配置。'],installation:['在支持 Sites 的 Codex 环境中使用。','提供页面目标、内容与需要的交互。'],example:'使用 $sites-building，根据方案文档实现一个三路由的静态产品网站，并保留移动端可用性。',output:'输出可运行的网站源码、构建结果与部署地址。',featured:false,updatedAt:null,kind:'site'},
  {slug:'deep-research',name:'深度研究',identifier:'deep-research',summary:'围绕明确问题检索多来源资料，整理证据并输出带引用的研究成果。',category:'研究与知识',tags:['研究','引用','报告'],compatibility:['Codex Work'],dependencies:['网络访问','可验证的信息来源'],limitations:['普通事实查询不需要使用；结论受公开资料范围限制。'],installation:['在支持 Deep Research 的工作模式中启用。','给出研究问题、范围、时间边界和交付格式。'],example:'使用 $deep-research，研究近两年端侧多模态模型的部署方法。比较内存、延迟与授权限制，并给出来源。',output:'输出结构化研究文档，关键结论附直接来源。',featured:false,updatedAt:null,kind:'research'},
  {slug:'remotion-voice-sync',name:'旁白视频同步',identifier:'remotion-voice-sync',summary:'以旁白时长为基准校准 Remotion 场景、字幕与背景音乐。',category:'音视频',tags:['Remotion','字幕','音频'],compatibility:['Codex','Remotion'],dependencies:['Node.js','FFmpeg','Remotion 项目'],limitations:['需要可访问的旁白文件；不替代人工审核发音与画面语义。'],installation:['将 SKILL 目录加入 Codex。','提供 Remotion 项目与最终旁白文件。'],example:'使用 $remotion-voice-sync，以 narration.wav 为准刷新各场景时长，生成句级字幕，并检查最终导出的音画漂移。',output:'刷新场景时间轴、字幕数据和导出校验结果。',featured:false,updatedAt:null,kind:'video'},
  {slug:'hugging-face-model-trainer',name:'模型训练任务',identifier:'hugging-face-model-trainer',summary:'准备数据并在 Hugging Face Jobs 上执行 SFT、DPO 或 GRPO 训练。',category:'模型与数据',tags:['Hugging Face','TRL','训练'],compatibility:['Codex','Hugging Face Jobs'],dependencies:['Hugging Face 账号与令牌','可用的云端 GPU 配额'],limitations:['训练会产生云端计算费用；数据许可与隐私需在提交前确认。'],installation:['安装并登录 Hugging Face CLI。','提供基础模型、数据集和训练方法。'],example:'使用 $hugging-face-model-trainer，在 Hugging Face Jobs 上对指定数据集执行 SFT。先验证数据，再估算硬件和费用。',output:'输出训练脚本、任务配置、监控入口与模型保存说明。',featured:false,updatedAt:null,kind:'model'}
];
const categories=['全部','设计与页面','开发工具','研究与知识','音视频','模型与数据'];
